from typing import Optional
from fastapi import HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from sqlalchemy.orm import selectinload

from app.models.sql.selection import Selection, SelectionNode
from app.models.sql.node import NodeVersion
from app.models.sql.document import DocumentVersion
from app.schemas.traceability import TraceabilityResponse, TraceabilityNodeDetail

LIMITATIONS_EXPLANATION = (
    "Hash-based stale detection has several key limitations:\n"
    "1. Semantic Equivalence (False Positives): Minor formatting updates, whitespace changes, "
    "or typo fixes change the content hash, causing the system to label the test cases as "
    "'Possibly stale' even if the core meaning remains identical and the test case is still fully valid.\n"
    "2. Out-of-Context Reordering (False Negatives): If a node is moved to a different section "
    "of the document where its meaning changes due to surrounding context, the content hash remains "
    "unchanged, causing it to report 'Fresh' when the test case might actually be invalid.\n"
    "3. Sibling/Parent Dependency (False Negatives): Test cases may rely on context from parent or "
    "sibling nodes. If those parent or sibling nodes change but the selected node remains the same, "
    "the selected node's hash does not change (reporting 'Fresh') despite the context being modified.\n"
    "4. Lack of Intent Understanding: Content hashes cannot evaluate whether a textual modification "
    "directly impacts the specific question/answer pair generated by the LLM."
)


async def check_traceability(
    selection_id: int,
    target_version_id: Optional[int],
    db: AsyncSession
) -> TraceabilityResponse:
    """
    Evaluates selection trace status by comparing original selection content hashes
    against a target version (or the latest version).
    """
    # 1. Fetch selection with document version and nodes
    stmt = (
        select(Selection)
        .options(
            selectinload(Selection.selection_nodes).selectinload(SelectionNode.logical_node),
            selectinload(Selection.document_version)
        )
        .where(Selection.id == selection_id)
    )
    res = await db.execute(stmt)
    selection = res.scalar_one_or_none()
    if not selection:
        raise HTTPException(
            status_code=404,
            detail=f"Selection with ID {selection_id} not found."
        )

    source_version = selection.document_version

    # 2. Determine target version
    if target_version_id is not None:
        stmt_tv = select(DocumentVersion).where(DocumentVersion.id == target_version_id)
        res_tv = await db.execute(stmt_tv)
        target_version = res_tv.scalar_one_or_none()
        if not target_version:
            raise HTTPException(
                status_code=404,
                detail=f"Target document version with ID {target_version_id} not found."
            )
        if target_version.document_id != source_version.document_id:
            raise HTTPException(
                status_code=400,
                detail=f"Target version {target_version_id} belongs to a different document."
            )
    else:
        # Get latest version for the same document
        stmt_latest = (
            select(DocumentVersion)
            .where(DocumentVersion.document_id == source_version.document_id)
            .order_by(DocumentVersion.version_number.desc())
            .limit(1)
        )
        res_latest = await db.execute(stmt_latest)
        target_version = res_latest.scalar_one_or_none()
        if not target_version:
            # Fallback to source version
            target_version = source_version

    # 3. Retrieve node versions for selection nodes in source version
    logical_node_ids = [sn.logical_node_id for sn in selection.selection_nodes]

    source_nvs = {}
    if logical_node_ids:
        stmt_snvs = (
            select(NodeVersion)
            .where(
                NodeVersion.logical_node_id.in_(logical_node_ids),
                NodeVersion.document_version_id == source_version.id
            )
        )
        res_snvs = await db.execute(stmt_snvs)
        source_nvs = {nv.logical_node_id: nv for nv in res_snvs.scalars().all()}

    # 4. Retrieve node versions for selection nodes in target version
    target_nvs = {}
    if logical_node_ids:
        stmt_tnvs = (
            select(NodeVersion)
            .where(
                NodeVersion.logical_node_id.in_(logical_node_ids),
                NodeVersion.document_version_id == target_version.id
            )
        )
        res_tnvs = await db.execute(stmt_tnvs)
        target_nvs = {nv.logical_node_id: nv for nv in res_tnvs.scalars().all()}

    # 5. Compare node statuses
    nodes_details = []
    has_removed = False
    has_modified = False

    for sn in selection.selection_nodes:
        logical_node_id = sn.logical_node_id
        logical_node_uuid = sn.logical_node.uuid
        source_nv = source_nvs.get(logical_node_id)
        target_nv = target_nvs.get(logical_node_id)

        source_hash = source_nv.content_hash if source_nv else None
        target_hash = target_nv.content_hash if target_nv else None

        if not target_nv:
            status_val = "removed"
            has_removed = True
        elif source_hash == target_hash:
            status_val = "unchanged"
        else:
            status_val = "modified"
            has_modified = True

        nodes_details.append(
            TraceabilityNodeDetail(
                logical_node_id=logical_node_id,
                logical_node_uuid=logical_node_uuid,
                status=status_val,
                source_content_hash=source_hash,
                target_content_hash=target_hash
            )
        )

    # Determine overall status
    if has_removed:
        overall_status = "Stale"
    elif has_modified:
        overall_status = "Possibly stale"
    else:
        overall_status = "Fresh"

    return TraceabilityResponse(
        status=overall_status,
        source_version_id=source_version.id,
        source_version_number=source_version.version_number,
        target_version_id=target_version.id,
        target_version_number=target_version.version_number,
        nodes=nodes_details,
        limitations=LIMITATIONS_EXPLANATION
    )
