"""Add generated test case model

Revision ID: 494d3f83d715
Revises: 9a155bbc56e9
Create Date: 2026-07-17 09:33:46.314431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494d3f83d715'
down_revision: Union[str, None] = '9a155bbc56e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('reference_context', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_test_cases_id'), 'generated_test_cases', ['id'], unique=False)
    op.create_index(op.f('ix_generated_test_cases_selection_id'), 'generated_test_cases', ['selection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_test_cases_selection_id'), table_name='generated_test_cases')
    op.drop_index(op.f('ix_generated_test_cases_id'), table_name='generated_test_cases')
    op.drop_table('generated_test_cases')
    # ### end Alembic commands ###
