"""Add versioned document models

Revision ID: 8d845b359728
Revises: None
Create Date: 2026-07-17 09:05:13.762214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d845b359728'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('commit_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_document_version_number')
    )
    op.create_index(op.f('ix_document_versions_id'), 'document_versions', ['id'], unique=False)
    op.create_table('logical_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logical_nodes_id'), 'logical_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_logical_nodes_uuid'), 'logical_nodes', ['uuid'], unique=True)
    op.create_table('node_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logical_node_id', sa.Integer(), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('parent_logical_node_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['logical_node_id'], ['logical_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_logical_node_id'], ['logical_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logical_node_id', 'document_version_id', name='uq_node_version_per_doc_version')
    )
    op.create_index(op.f('ix_node_versions_content_hash'), 'node_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_node_versions_id'), 'node_versions', ['id'], unique=False)
    op.create_table('selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selections_id'), 'selections', ['id'], unique=False)
    op.create_table('selection_nodes',
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.Column('logical_node_id', sa.Integer(), nullable=False),
    sa.Column('selected_text', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['logical_node_id'], ['logical_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('selection_id', 'logical_node_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selection_nodes')
    op.drop_index(op.f('ix_selections_id'), table_name='selections')
    op.drop_table('selections')
    op.drop_index(op.f('ix_node_versions_id'), table_name='node_versions')
    op.drop_index(op.f('ix_node_versions_content_hash'), table_name='node_versions')
    op.drop_table('node_versions')
    op.drop_index(op.f('ix_logical_nodes_uuid'), table_name='logical_nodes')
    op.drop_index(op.f('ix_logical_nodes_id'), table_name='logical_nodes')
    op.drop_table('logical_nodes')
    op.drop_index(op.f('ix_document_versions_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
