"""Add LLM failure model

Revision ID: 9a155bbc56e9
Revises: 8d845b359728
Create Date: 2026-07-17 09:28:47.060348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a155bbc56e9'
down_revision: Union[str, None] = '8d845b359728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_generation_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_generation_failures_id'), 'llm_generation_failures', ['id'], unique=False)
    op.create_index(op.f('ix_llm_generation_failures_selection_id'), 'llm_generation_failures', ['selection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_generation_failures_selection_id'), table_name='llm_generation_failures')
    op.drop_index(op.f('ix_llm_generation_failures_id'), table_name='llm_generation_failures')
    op.drop_table('llm_generation_failures')
    # ### end Alembic commands ###
